# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b73cd6592452438861a32740254e4dc155e1a7873aa74c9249bd798b108f054a113d4f517accaf4ccf263782ce1013c43caef772bf845e2bb8f9e7fb3aa6ef6

test:
  secret_key_base: 2929f6fafbb5e6ca365ea2db140be9a540a660774fd79f206957537178f4cb4df8d66b15a796b68a41add06b236225668e3889f84a09fcea316ef28a846483f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
